services:

    postgres:
        image: postgres:16-alpine
        container_name: postgres_db
        volumes:
        - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password

    keycloak_web:
        image: quay.io/keycloak/keycloak:23.0.7
        container_name: keycloak_web
        environment:
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
            KC_DB_USERNAME: keycloak
            KC_DB_PASSWORD: password

            KC_HOSTNAME: localhost
            KC_HOSTNAME_STRICT: false
            KC_HOSTNAME_STRICT_HTTPS: false

            KC_LOG_LEVEL: info
            KC_METRICS_ENABLED: true
            KC_HEALTH_ENABLED: true
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        command: start-dev
        depends_on:
        - postgres
        ports:
        - 8180:8080

volumes:
  postgres_data:
